# Generated by Django 5.2.4 on 2025-08-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimeter', models.FloatField(default=3.5)),
                ('travel_speed_threshold', models.FloatField(default=10)),
                ('company_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('daily_working_hours', models.IntegerField(default=8)),
                ('work_summary_interval', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=10)),
                ('company_img', models.ImageField(upload_to='company_images')),
                ('punch_mode', models.CharField(choices=[('S', 'Single Punch'), ('M', 'Multiple Punch')], default='S', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('check-in', 'Check-in'), ('check-out', 'Check-out')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_device', models.CharField(max_length=200, unique=True)),
                ('physical_device', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hour', models.FloatField(blank=True, null=True)),
                ('company', models.ManyToManyField(related_name='roles', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ManyToManyField(blank=True, to='company.company')),
            ],
        ),
    ]
