# Generated by Django 5.2.4 on 2025-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygroup',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
