# Generated by Django 5.2.4 on 2025-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companygroup_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
