# Generated by Django 5.2.4 on 2025-08-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyuser_company_alter_companyuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companygroup'),
        ),
    ]
