# Generated by Django 5.2.4 on 2025-08-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_companyuser_role_alter_companyuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyrole'),
        ),
    ]
