# Generated by Django 5.2.4 on 2025-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
