# Generated by Django 5.2.4 on 2025-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companyuser_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygroup',
            name='only_visible_to_lead',
            field=models.BooleanField(default=False),
        ),
    ]
