# Generated by Django 5.2.4 on 2025-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companygroup_only_visible_to_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('check-In', 'Check-In'), ('check-Out', 'Check-Out')], max_length=15, null=True),
        ),
    ]
