# Generated by Django 5.2.4 on 2025-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_device_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], max_length=15, null=True),
        ),
    ]
