# Generated by Django 5.2.4 on 2025-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_device_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygroup',
            name='group',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
