# Generated by Django 5.2.4 on 2025-08-11 17:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_companygroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=100)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('late_allowance', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
