# Generated by Django 5.2.4 on 2025-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'colleges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'machines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('college_code', models.CharField(max_length=20)),
                ('jwt_token', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='allow_individual_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='allow_individual_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='soft_disable',
            field=models.BooleanField(default=False, help_text='Disable all SMS & WhatsApp services when True'),
        ),
        migrations.AddField(
            model_name='company',
            name='strict_sms',
            field=models.BooleanField(default=False, help_text='Force enable SMS for all employees'),
        ),
        migrations.AddField(
            model_name='company',
            name='strict_whatsapp',
            field=models.BooleanField(default=False, help_text='Force enable WhatsApp for all employees'),
        ),
    ]
