# Generated by Django 5.2.4 on 2025-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_college_machine_user_company_allow_individual_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
