# Generated by Django 5.2.7 on 2026-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aicte_approved',
            field=models.BooleanField(default=False),
        ),
    ]
