# Generated by Django 5.2.7 on 2026-07-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_company_aicte_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('staff_id_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('start_id', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_configs', to='company.company')),
            ],
            options={
                'unique_together': {('company',)},
            },
        ),
    ]
