# Generated by Django 5.2.7 on 2026-08-13 05:43
# Manually updated to safely populate unique UUIDs for existing rows.

import uuid
from django.db import migrations, models


def populate_uuid(apps, schema_editor):
    """Assign a unique UUID to every existing Company row."""
    Company = apps.get_model('company', 'Company')
    for company in Company.objects.filter(id_uuid__isnull=True):
        company.id_uuid = uuid.uuid4()
        company.save(update_fields=['id_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_companyfieldsetting'),
    ]

    operations = [
        # Step 1: Add the column as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='company',
            name='id_uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        # Step 2: Populate a unique UUID for every existing row
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
        # Step 3: Enforce NOT NULL + UNIQUE now that all rows have a value
        migrations.AlterField(
            model_name='company',
            name='id_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
