# Generated by Django 5.2.4 on 2025-07-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('punch_time', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], max_length=10, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'punch_records',
            },
        ),
        migrations.CreateModel(
            name='VirtualPunchRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('punch_time', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_device', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
