# Generated by Django 5.2.4 on 2025-08-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyshift'),
        ('punch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('shift1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_shift1', to='company.companyshift')),
                ('shift2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_shift2', to='company.companyshift')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
