# Generated by Django 5.2.7 on 2026-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0002_shiftswap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchrecords',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
