# Generated by Django 5.2.4 on 2025-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyuser_group_companyuser_role_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent_company',
            field=models.ManyToManyField(blank=True, related_name='users_parent_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='users_company', to='company.company'),
        ),
    ]
