# Generated by Django 5.2.4 on 2025-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_parent_company_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
