# Generated by Django 5.2.4 on 2025-08-08 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companygroup_only_visible_to_lead'),
        ('user', '0003_customuser_team_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent_company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
