# Generated by Django 5.2.4 on 2025-08-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyshift'),
        ('user', '0004_remove_customuser_parent_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyshift'),
        ),
    ]
