# Generated by Django 5.2.4 on 2025-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_working_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_calculated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
