# Generated by Django 5.2.4 on 2025-08-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_avg_working_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_calculated_date',
            new_name='last_VG_calculated_date',
        ),
    ]
