# Generated by Django 5.2.4 on 2025-08-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_last_calculated_date_customuser_last_vg_calculated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_VG_calculated_date',
            new_name='last_avg_calculated_date',
        ),
    ]
