# Generated by Django 5.2.4 on 2025-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_last_vg_calculated_date_customuser_last_avg_calculated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_days_count',
            field=models.IntegerField(default=0),
        ),
    ]
