# Generated by Django 5.2.4 on 2025-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_avg_days_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avg_working_hour',
            new_name='montly_avg_working_hour',
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_avg_working_hour',
            field=models.FloatField(default=0),
        ),
    ]
