# Generated by Django 5.2.4 on 2025-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_avg_working_hour_customuser_montly_avg_working_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avg_days_count',
            new_name='monthly_days_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_days_count',
            field=models.IntegerField(default=0),
        ),
    ]
