# Generated by Django 5.2.4 on 2025-08-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_avg_days_count_customuser_monthly_days_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='montly_avg_working_hour',
            new_name='monthly_avg_working_hour',
        ),
    ]
