# Generated by Django 5.2.7 on 2026-06-08 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_employeeexperience_employeequalification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='acc_holder_fname',
            new_name='acc_holder_name',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='acc_holder_lname',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='acc_holder_mname',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='guardian_phone',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_contract_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_relieving',
            field=models.DateField(blank=True, help_text='Date of Relieving / Termination / Retirement', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('other', 'Other')], default='other', max_length=20)),
                ('is_guardian', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
