# Generated by Django 5.2.7 on 2026-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_acc_holder_fname_bankdetail_acc_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeequalification',
            options={'ordering': ['-completion_date']},
        ),
        migrations.RemoveField(
            model_name='employeequalification',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='employeequalification',
            name='start_year',
        ),
        migrations.AddField(
            model_name='employeequalification',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Passing Year / Certification / Completion Date', null=True),
        ),
        migrations.AddField(
            model_name='employeequalification',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course Start Date / Enrollment Date', null=True),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='institution_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='percentage',
            field=models.FloatField(blank=True, help_text='Percentage or CGPA (Leave blank for Research/Ph.D.)', null=True),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='qualification_level',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('MPHIL', 'M.Phil.'), ('PHD', 'Ph.D.'), ('POSTDOC', 'Post Doctoral (Post.Doc)'), ('RESEARCH_OTHERS', 'Research (Others)'), ('OTHERS', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='specialization',
            field=models.CharField(help_text='Degree/Course name', max_length=150),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='university',
            field=models.CharField(max_length=255),
        ),
    ]
