# Generated by Django 5.2.7 on 2026-06-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_companyprofile'),
        ('user', '0017_alter_employeequalification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Designates if this career timeline experience is within the current company'),
        ),
        migrations.AddField(
            model_name='experiencedesignation',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_designations', to='company.companygroup'),
        ),
        migrations.AddField(
            model_name='experiencedesignation',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_designations', to='company.companyrole'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company_name',
            field=models.CharField(blank=True, help_text='Leave blank or fill if external', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedesignation',
            name='change_type',
            field=models.CharField(choices=[('Joined', 'Joined'), ('Promotion', 'Promotion'), ('Demotion', 'Demotion'), ('Re-designation', 'Re-designation')], default='Joined', max_length=20),
        ),
        migrations.AlterField(
            model_name='experiencedesignation',
            name='designation',
            field=models.CharField(blank=True, help_text='Raw text entry for external history', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedesignation',
            name='start_date',
            field=models.DateField(help_text='Effective date of this designation state'),
        ),
    ]
