# Generated by Django 5.2.7 on 2026-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_employeeexperience_is_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
