# Generated by Django 5.2.7 on 2026-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_employeeprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='category',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Institution', 'Institution'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='is_after_pg',
            field=models.BooleanField(default=False, help_text='Check if this experience was acquired AFTER acquiring your PG degree'),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='is_aicte_approved',
            field=models.BooleanField(default=False),
        ),
    ]
