# Generated by Django 5.2.7 on 2026-07-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_candidateapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
