# Generated by Django 5.2.7 on 2026-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_employeeprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_head',
            field=models.BooleanField(default=False),
        ),
    ]
