# Generated by Django 5.2.7 on 2026-07-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_staffidconfig'),
        ('user', '0023_customuser_company_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_data', models.JSONField(default=dict)),
                ('last_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_drafts', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'created_by')},
            },
        ),
    ]
