# Generated by Django 5.2.7 on 2026-10-01 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_id_uuid'),
        ('user', '0024_employeeonboardingdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('joined', 'Joined'), ('transfer', 'Department / Group Transfer'), ('promotion', 'Promotion'), ('demotion', 'Demotion'), ('redesignation', 'Re-designation'), ('relieving', 'Relieving / Resignation'), ('correction', 'Correction'), ('other', 'Other')], max_length=20)),
                ('effective_date', models.DateField(help_text='Date the event actually took effect (not when it was entered)')),
                ('corrected_field', models.CharField(blank=True, help_text="Name of the field that was corrected (e.g. 'date_of_joining')", max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra info (e.g. order letter number, reference)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_changes_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_history_events', to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to=settings.AUTH_USER_MODEL)),
                ('from_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_group', to='company.companygroup')),
                ('from_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_role', to='company.companyrole')),
                ('to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_group', to='company.companygroup')),
                ('to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_role', to='company.companyrole')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'event_type'], name='user_employ_employe_3de84c_idx'), models.Index(fields=['company', 'effective_date'], name='user_employ_company_da5daa_idx')],
            },
        ),
    ]
