# Generated by Django 5.2.4 on 2025-08-01 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_global', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_full_holiday', models.BooleanField(default=False)),
                ('company', models.ManyToManyField(blank=True, related_name='holidays', to='company.company')),
                ('role', models.ManyToManyField(to='company.companyrole')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_limit', models.FloatField(blank=True, null=True)),
                ('yearly_limit', models.FloatField(blank=True, null=True)),
                ('initial_credit', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False)),
                ('use_credit', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField(default=0)),
                ('year', models.IntegerField(default=2025)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_taken', models.FloatField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_choice', models.CharField(choices=[('F', 'Full day'), ('H', 'Half day')], max_length=70)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Cancelled')], max_length=50)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
        ),
    ]
