# Generated by Django 5.2.4 on 2025-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_carry_forward',
            field=models.BooleanField(default=True),
        ),
    ]
