# Generated by Django 5.2.7 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavetype_allow_carry_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecredit',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
