# Generated by Django 5.2.7 on 2026-07-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_staffidconfig'),
        ('leave', '0003_alter_leavecredit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_trail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='LeaveFlowHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_config', models.JSONField(blank=True, default=list, help_text='Stores ordered user IDs or steps between team lead and company head')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_hierarchy', to='company.company')),
            ],
        ),
    ]
