# Generated by Django 5.2.7 on 2026-07-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0020_staffidconfig"),
        ("leave", "0003_alter_leavecredit_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_limit", models.FloatField(blank=True, null=True)),
                ("yearly_limit", models.FloatField(blank=True, null=True)),
                ("initial_credit", models.FloatField(default=0)),
                ("allow_carry_forward", models.BooleanField(default=True)),
                ("use_credit", models.BooleanField(default=False)),
                ("custom_settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="company.company",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "staff_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="company.staffcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave Policies",
                "unique_together": {("company", "staff_category", "leave_type")},
            },
        ),
    ]
