# Generated by Django 5.2.7 on 2026-07-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_approval_trail_leaveflowhierarchy'),
        ('leave', '0004_leavepolicy'),
    ]

    operations = [
    ]
