# Generated by Django 5.2.7 on 2026-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_merge_20260729_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='policy_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('staff_category', 'Staff Category')], default='normal', max_length=20),
        ),
    ]
