# Generated by Django 5.2.7 on 2026-07-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0007_leave_replacement_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="ta_da_payable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="has_ta_da",
            field=models.BooleanField(default=False),
        ),
    ]
