# Generated by Django 5.2.7 on 2026-07-31 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0008_leave_ta_da_payable_leavepolicy_has_ta_da"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
