# Generated by Django 5.2.7 on 2026-08-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leave_current_approver_leave_current_level'),
        ('leave', '0009_leave_current_approver_leave_current_level'),
    ]

    operations = [
    ]
