# Generated by Django 5.2.4 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0011_alter_leave_current_approver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]