# Generated by Django 6.1.2 on 2026-10-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_companyshift_staff_type'),
        ('leave', '0012_leavetype_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year this balance applies to')),
                ('snapshot_date', models.DateField(help_text='The cut-off date the client supplied the balance for (leaves after this date are deducted from opening_balance)')),
                ('opening_balance', models.FloatField(help_text='Leave balance as of snapshot_date, as imported from Excel')),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_leave_balances', to='company.company')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_balances', to='leave.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imported Leave Balance',
                'verbose_name_plural': 'Imported Leave Balances',
                'unique_together': {('user', 'leave_type', 'company', 'year')},
            },
        ),
    ]
