# Generated by Django 5.2.7 on 2026-10-10 07:06

from datetime import date

from django.db import migrations, models


def backfill_year_end_expiry(apps, schema_editor):
    """Give already-imported balances a default expiry of their year end."""
    ImportedLeaveBalance = apps.get_model('leave', 'ImportedLeaveBalance')
    ImportedLeaveBalance.objects.filter(
        expiry_date__isnull=True, year=2026
    ).update(expiry_date=date(2026, 12, 31))


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_imported_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedleavebalance',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional last date this imported balance remains in use. It is applied while today <= expiry_date; from the next day the system falls back to the computed balance (the row is kept, never deleted).', null=True),
        ),
        migrations.RunPython(backfill_year_end_expiry, migrations.RunPython.noop),
    ]
